### ISSUE TITLE
How can I build the libdlib.so?

### ISSUE THREAD

**Issue by Sanqi5401** [githubzhy/dlib_android_compile#1]
I want to update the libdlib.so. How can I do it?

**Comment by githubzhy** [comment]
ubuntu 编译步骤：
 1, cd /build/dlib_android/ 
2, vim build.sh 确认 ANDROID_NDK 和你自己的android ndk目录和版本是否一致 
3, ./build.sh

PS:  编译成功后，将在 android-cmake/build/dlib_android/dlib目录下生成 libdlib.a libdlib.so
